(changed) overlay registry is moved to /var/lib/vcpkg-deb (#4)

diff --git a/vcpkg-deb/DEBIAN/postrm b/vcpkg-deb/DEBIAN/postrm
--- a/vcpkg-deb/DEBIAN/postrm
+++ b/vcpkg-deb/DEBIAN/postrm
@@ -3,11 +3,11 @@ set -e
 
 case "$1" in
   remove)
-    rmdir --ignore-fail-on-non-empty /usr/share/vcpkg-deb 2>/dev/null || true
+    rmdir --ignore-fail-on-non-empty /var/lib/vcpkg-deb 2>/dev/null || true
     ;;
   purge)
-    rm -rf /usr/share/vcpkg-deb || {
-	  echo "Warning: failed to remove /usr/share/vcpkg-deb" >&2
+    rm -rf /var/lib/vcpkg-deb || {
+	  echo "Warning: failed to remove /var/lib/vcpkg-deb" >&2
 	  true
 	}
     ;;
